# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=55)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commerce.advertiser')),
            ],
        ),
    ]
